### ISSUE TITLE
Pattern-match spotting needs to enable after "and" etc

### ISSUE THREAD

**Issue by mohawk2** [steve-m-hay/Text-Balanced#7]
`$RE_PREREGEX_PAT` needs enhancing with at least `and`, plus any other builtin keywords that can be followed by an expression, to fix a false negative for:

```perl
    for (@entries) { $_ = $opt{MISSN} unless defined $_ and /\d\b/ }
```

That can at least be worked around by prefixing regexes with `m`, but it's not ideal.

Having recently re-watched Damian's "Three Little Words" (https://www.youtube.com/watch?v=e1T7WbKox6s) which mentions https://metacpan.org/pod/PPR, it might be beneficial to use that here to simplify the various types of matching this module does. @steve-m-hay Would such a concept be viable given that T:B has an existence in Perl core, meaning PPR would also need to be incorporated?

**Comment by steve-m-hay** [comment]
> Having recently re-watched Damian's "Three Little Words" (https://www.youtube.com/watch?v=e1T7WbKox6s) which mentions https://metacpan.org/pod/PPR, it might be beneficial to use that here to simplify the various types of matching this module does. @steve-m-hay Would such a concept be viable given that T:B has an existence in Perl core, meaning PPR would also need to be incorporated?

Your best bet is probably to ask on p5p, but there is usually resistance to incorporating more things into Perl core. I doubt there is a strong enough case for this, but there's never any harm in asking.

Would it be possible to code things in such a way that PPR can be taken advantage of if it's available, but otherwise we fall back on traditional methods? Or is that just making too much extra work and complication?

**Comment by mohawk2** [comment]
My feeling is that a library that behaves differently depending on what deps are installed is a bit of a tricky proposition. One view is it could behave better but gracefully fall back; the other is it's a bit "action at a distance".

Given the likely resistance from p5p (which I both understand and actually share in this case, if that makes sense), together with the labour and complexity involved in changing it over but still having a fallback (and the benefit would mostly have been in stopping trying to do parsing of Perl in the ad-hoc way it currently is), the apparent best way forward is just to add the cases to the regex as identified in this issue.

I'll probably do that before I deal with Filter::Simple, since this trail is already "blazed", though I can see benefits to initiating the F:S change first given the likely delay in coordinating with Steffen. On that point, you wouldn't happen to have comms with him?

**Comment by steve-m-hay** [comment]
[Reposting on GH since I'm not sure my email reply has come through?]

> I'll probably do that before I deal with Filter::Simple, since this trail is already "blazed", though I can see benefits to initiating the F:S change first given the likely delay in coordinating with Steffen. On that point, you wouldn't happen to have comms with him?

I don't think I've had communication with Steffen before, but he just happens to be the last person to have released the module on CPAN anyway. It's actually now maintained by p5p so I think any core committer could make a new release, any of whom are more active in Perl than Steffen now - he doesn't appear to have uploaded anything to CPAN in the last 5 years.

**Comment by mohawk2** [comment]
> [Reposting on GH since I'm not sure my email reply has come through?]

It didn't, so thank you.

**Comment by steve-m-hay** [comment]
On Mon, 23 May 2022, 20:19 mohawk2, ***@***.***> wrote:

> I'll probably do that before I deal with Filter::Simple, since this trail
> is already "blazed", though I can see benefits to initiating the F:S change
> first given the likely delay in coordinating with Steffen. On that point,
> you wouldn't happen to have comms with him?
>
I don't think I've had communication with Steffen before, but he just
happens to be the last person to have released the module on CPAN anyway.
It's actually now maintained by p5p so I think any core committer could
make a new release, any of whom are more active in Perl than Steffen now -
he doesn't appear to have uploaded anything to CPAN in the last 5 years.

>
